# Generated by Django 4.2.23 on 2025-07-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_msg',
            field=models.TextField(default='Sizning akkauntingiz bloklangan. Iltimos, admin bilan bog‘laning.', verbose_name='Blocked Message'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_blocked',
            field=models.BooleanField(default=False, verbose_name='Is Blocked'),
        ),
    ]
