# Generated by Django 4.2.23 on 2025-07-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_id_blocked_customuser_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('pending', 'Tasdiqlash kutilmoqda'), ('active', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=10),
        ),
    ]
