# Generated by Django 4.2 on 2025-07-24 16:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('terms', 'Terms & Conditions'), ('privacy', 'Privacy Policy')], max_length=100, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
