# Generated by Django 4.2 on 2025-07-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitepolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sitepolicy',
            name='title',
            field=models.CharField(choices=[('terms', 'Foydalanish shartlari'), ('privacy', 'Mahfiylik siyosati')], max_length=100, unique=True),
        ),
    ]
